[project]
name = "cer-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "django>=5.1.7",
    "django-environ>=0.12.0",
    "django-tailwind[reload]>=3.8.0",
    "psycopg>=3.2.6",
]
